apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linkboard-backend
  namespace: linkboard
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: linkboard-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
